apiVersion: v1
kind: Service
metadata: 
  name: wordpress-mysql
  labels:
    app: wordpress
spec: 
  ports: 
  - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None

---

apiVersion: app/v1beta2    #for version before 1.8.0 use app/v1beta1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: myapp
      tier: mysql
  strategy: 
    type: Recreate    
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: PASSWORDS_IN_PLAIN_TEXT_ARE_BAD_WE_WILL_SHOW_SHOETHING_MORE_SECURE          
          ports:
        - containerPort: 3306
          name: mysql

